-- SUPABASE DATABASE SCHEMA FOR DOMPETKU (CATATAN KEUANGAN)
-- Copy and paste this script into your Supabase SQL Editor and run it to set up the tables and RLS policies.

-- 1. Table: profil
CREATE TABLE public.profil (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  nama text NOT NULL,
  icon text DEFAULT 'person',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 2. Table: dompet
CREATE TABLE public.dompet (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  nama text NOT NULL,
  saldo double precision DEFAULT 0,
  warna text NOT NULL,
  currency text DEFAULT 'IDR',
  profil_id bigint
);

-- 3. Table: kategori
CREATE TABLE public.kategori (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users, -- Nullable for global default categories
  nama text NOT NULL,
  jenis text NOT NULL,
  icon text DEFAULT 'category',
  is_default boolean DEFAULT false
);

-- 4. Table: budget
CREATE TABLE public.budget (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  bulan integer NOT NULL,
  tahun integer NOT NULL,
  nominal double precision NOT NULL,
  kategori text NOT NULL,
  profil_id bigint,
  sisa_rollover double precision DEFAULT 0,
  CONSTRAINT budget_user_period_kategori_key UNIQUE (user_id, bulan, tahun, kategori)
);

-- 5. Table: transaksi
CREATE TABLE public.transaksi (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  jenis text NOT NULL,
  jumlah double precision NOT NULL,
  deskripsi text NOT NULL,
  kategori text NOT NULL,
  tanggal timestamp with time zone NOT NULL,
  id_dompet bigint,
  is_recurring boolean DEFAULT false,
  recurring_frequency text,
  lampiran text,
  deleted_at timestamp with time zone
);

-- 6. Table: utang_piutang
CREATE TABLE public.utang_piutang (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  nama_orang text NOT NULL,
  jenis text NOT NULL,
  nominal_total double precision NOT NULL,
  nominal_dibayar double precision DEFAULT 0,
  tanggal timestamp with time zone NOT NULL,
  tenggat_waktu timestamp with time zone,
  deskripsi text,
  is_lunas boolean DEFAULT false
);

-- 7. Table: history_cicilan
CREATE TABLE public.history_cicilan (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  id_utang_piutang bigint REFERENCES public.utang_piutang(id) ON DELETE CASCADE,
  nominal double precision NOT NULL,
  tanggal timestamp with time zone NOT NULL
);

-- 8. Table: tabungan_impian
CREATE TABLE public.tabungan_impian (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  nama_impian text NOT NULL,
  target_nominal double precision NOT NULL,
  terkumpul double precision DEFAULT 0,
  target_tanggal timestamp with time zone,
  icon text DEFAULT 'savings'
);

-- 9. Table: pengaturan
CREATE TABLE public.pengaturan (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  is_dark_mode boolean DEFAULT false,
  pin text,
  use_biometric boolean DEFAULT false
);

-- ===========================================================================
-- ENABLE ROW LEVEL SECURITY (RLS)
-- ===========================================================================
ALTER TABLE public.profil ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dompet ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kategori ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.budget ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transaksi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.utang_piutang ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.history_cicilan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tabungan_impian ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pengaturan ENABLE ROW LEVEL SECURITY;

-- ===========================================================================
-- RLS POLICIES (Users can only access their own data)
-- ===========================================================================

-- Profil Policies
CREATE POLICY "Users can manage their own profile" ON public.profil
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Dompet Policies
CREATE POLICY "Users can manage their own wallets" ON public.dompet
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Kategori Policies (Allow viewing global defaults and managing user-specific categories)
CREATE POLICY "Users can view default categories and manage their own" ON public.kategori
  FOR ALL TO authenticated USING (user_id IS NULL OR auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Budget Policies
CREATE POLICY "Users can manage their own budgets" ON public.budget
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Transaksi Policies
CREATE POLICY "Users can manage their own transactions" ON public.transaksi
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Utang Piutang Policies
CREATE POLICY "Users can manage their own debts/receivables" ON public.utang_piutang
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- History Cicilan Policies
CREATE POLICY "Users can manage their own payment history" ON public.history_cicilan
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Tabungan Impian Policies
CREATE POLICY "Users can manage their own savings goals" ON public.tabungan_impian
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Pengaturan Policies
CREATE POLICY "Users can manage their own settings" ON public.pengaturan
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
