name: CI

on:
  pull_request:
    branches: [ main, 'release/v*' ]

jobs:
  analyze:
    name: Flutter Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0
          cache: true
          pub-cache: true
      - run: flutter pub get
      - run: flutter analyze

  test:
    name: Flutter Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0
          cache: true
          pub-cache: true
      - run: flutter pub get
      - run: flutter test --no-pub
